// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coreuygulama.Data;

#nullable disable

namespace coreuygulama.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250616110615_createDb")]
    partial class createDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("coreuygulama.Models.Kitaplar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("YazarId")
                        .HasColumnType("int");

                    b.Property<int>("basimyili")
                        .HasColumnType("int");

                    b.Property<string>("kitapadi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("turid")
                        .HasColumnType("int");

                    b.Property<int>("turlerid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("YazarId");

                    b.HasIndex("turlerid");

                    b.ToTable("Kitaplars");
                });

            modelBuilder.Entity("coreuygulama.Models.Turler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("kitapturu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Turlers");
                });

            modelBuilder.Entity("coreuygulama.Models.Yazarlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("YazarBilgi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YazarId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Yazarlars");
                });

            modelBuilder.Entity("coreuygulama.Models.Kitaplar", b =>
                {
                    b.HasOne("coreuygulama.Models.Yazarlar", "yazar")
                        .WithMany("Kitaplar")
                        .HasForeignKey("YazarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("coreuygulama.Models.Turler", "turler")
                        .WithMany("kitaplar")
                        .HasForeignKey("turlerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("turler");

                    b.Navigation("yazar");
                });

            modelBuilder.Entity("coreuygulama.Models.Turler", b =>
                {
                    b.Navigation("kitaplar");
                });

            modelBuilder.Entity("coreuygulama.Models.Yazarlar", b =>
                {
                    b.Navigation("Kitaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
