//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db_First_Prosedurlu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_first_prosedurEntities3 : DbContext
    {
        public db_first_prosedurEntities3()
            : base("name=db_first_prosedurEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Araclar> Araclars { get; set; }
    
        public virtual int Guncelleme(Nullable<int> id, string marka, string model, string renk)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var markaParameter = marka != null ?
                new ObjectParameter("marka", marka) :
                new ObjectParameter("marka", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            var renkParameter = renk != null ?
                new ObjectParameter("renk", renk) :
                new ObjectParameter("renk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Guncelleme", idParameter, markaParameter, modelParameter, renkParameter);
        }
    
        public virtual int Kaydetme(string marka, string model, string renk)
        {
            var markaParameter = marka != null ?
                new ObjectParameter("marka", marka) :
                new ObjectParameter("marka", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            var renkParameter = renk != null ?
                new ObjectParameter("renk", renk) :
                new ObjectParameter("renk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Kaydetme", markaParameter, modelParameter, renkParameter);
        }
    
        public virtual ObjectResult<Listeleme_Result> Listeleme()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Listeleme_Result>("Listeleme");
        }
    
        public virtual int Silme(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Silme", idParameter);
        }
    
        public virtual ObjectResult<Ara_Result> Ara(string arananmetin)
        {
            var arananmetinParameter = arananmetin != null ?
                new ObjectParameter("arananmetin", arananmetin) :
                new ObjectParameter("arananmetin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ara_Result>("Ara", arananmetinParameter);
        }
    }
}
