//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kütüphane_modelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islemler
    {
        public short Id { get; set; }
        public string AlısTarihi { get; set; }
        public string VerişTarihi { get; set; }
        public long UyelerTc { get; set; }
        public int KitaplarKitapNo { get; set; }
    
        public virtual Uyeler Uyeler { get; set; }
        public virtual Kitaplar Kitaplar { get; set; }
    }
}
